### PR TITLE
[SDL 0200] - Removing url parameter max length

### LINKED ISSUE #252: [SDL 0200] - Removing URL Parameter Max Length
Proposal: [Removing URL Parameter Max Length](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0200-Removing-URL-Param-Max-Length.md)

> This proposal is to remove maximum length attribute for URL strings provided to OnSystemRequest, StartStream and StartAudioStream and let the URL strings be of any length permissible by the system architecture.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/603

Steering Committee Decision:

> The Steering Committee accepted this proposal on 10/16/2018. The following was discussed in the Steering Committee meeting on 2018-10-16, with regards to this proposal: Although there are no iOS or Android limitations over the size and length of URLs, excessively long ones may take a long time to create / parse, and extensive data should be sent via a method that is not a URL (e.g. JSON in the bulk data).
Lastly, while it's understood that SDLC members cannot share all use cases for features publicly, it was acknowledged that in the future, when requesting specific features, it is helpful to have real world examples to better understand the reasoning and planned implementation for the requested changes.

### PR DESCRIPTION
**Pull request by vladmu**
Fixes #252

This PR is **[ready]** for review.

### Risk
This PR makes **[no]** API changes.

### Summary
This PR doesn't provide any library changes. Still, it gives unit tests that cover `OnSystemRequest` class itself with additional checking of the `url` parameter to be sure it is not changed in the library over the `set`/`get` process.

##### Enhancements
* New unit tests added for OnSystemRequest class

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform) and this pull request adheres to the [Contributing Guide](./CONTRIBUTING.md).

### CODE REVIEW

**Comment by vladmu** [comment]
@santhanamk @atiwari9 please read the long conversation in the issue #252 then review this PR. I hope I understood PMs correctly with this change. Thank you!

**Comment by vladmu** [comment]
> Hi @vladmu. I reviewed the PR, and it looks good.
> 
> Along with OnSystemRequest, the proposal mentions StartStream and StartAudioStream. Do unit tests need to be added for those as well?
No, StartStream and StartAudioStream in the proposal both are related to HMI_API, therefore they are out of the library scope.

**Comment by santhanamk** [comment]
Hi @theresalech this PR is ready for Livio review.

**Comment by crokita** [comment]
What's here looks good. I would like to see some extra cases for the URL string being set:
- Setting the URL to an empty string
- Setting the URL to a string exactly the length of the old limit (1000 characters)

With the current tests and the suggestions above, this will be a suitable set of tests for OnSystemRequest for the JavaScript Suite, since the library does not use the RPC internally. Note that the other mobile libraries use OnSystemRequest for policy retrieval and so they will need additional tests for the application of the RPC.

**Comment by vladmu** [comment]
@crokita, please review my last commit, I've added the extra cases you described. I suppose we could use this codebase for Android and Java as the start point, at least, and then additional tests could be discussed separately in each particular PR. Please approve then we could switch to them.

**Comment by vladmu** [comment]
@crokita is it possible to merge this PR due to your previous approval and the release 1.1.0 announcement?

**Pull request merged**
