### PR TITLE
apply reserved keywords mapping

### PR DESCRIPTION
**Pull request by o-mishch**
Fixes https://github.com/smartdevicelink/sdl_javascript_suite/issues/2
This PR is **ready** for review.

**Risk**
This PR makes **no** API changes.

**Testing Plan**
Verify test app connectivity and that all unit tests pass.

**Summary**
avoid using keywords when generating RPC definitions.

**CLA**
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform) and this pull request adheres to the [Contributing Guide](./CONTRIBUTING.md).

### CODE REVIEW

**Comment by o-mishch** [comment]
@nickschwab please review this PR

**Comment by o-mishch** [comment]
@mrapitis, @nickschwab please review this PR

**Comment by theresalech** [comment]
@mrapitis please let us know once you've reviewed.  Then @crokita will start his review.  Thanks!

**Comment by mrapitis** [comment]
@theresalech Ford has reviewed and approved this PR.

**Comment by crokita** [comment]
This is the feedback I have so far for when using the generator.

Capitalization overriding rules should only apply to the class names, and not to the enumerated values or to the methods that access them. See the following enums whose getter method names get capitalized:
	- ImageFieldName
	- MetadataType
	- TextFieldName
	- MessageType

I noticed some inconsistencies in application of the method name changes. Some also have changed the static key values to include PARAM (ex. VehicleDataResult's getResultCodeParam uses KEY_RESULT_CODE_PARAM, but in TouchEvent for getIdParam the key doesn't change. This isn't the only case).

**Comment by o-mishch** [comment]
@crokita In `RESERVED_KEYWORDS` there are keywords `KEY_RESULT_CODE` and `getResultCode`, that’s why it was replaced appropriately in VehicleDataResult.
as well there is keyword `id`, but there wasn’t keyword `KEY_ID`, then’s why was changed only `getidParam` in TouchEvent

**Comment by crokita** [comment]
Thanks for the clarification. The last part of my post can be ignored, then.

**Comment by o-mishch** [comment]
@crokita issue with capitalisation on enum getters resolved in https://github.com/smartdevicelink/sdl_javascript_suite/pull/181/commits/13e04edbcf1f2f91971d164e6a122e90bd2646c5

**Comment by crokita** [comment]
Tested the changes and things look good. I'm going to change the base to our release branch since we have a release candidate ready for review and revisions.

**Pull request merged**
