### PR TITLE
[SDL 0266] New vehicle data GearStatus

### LINKED ISSUE #255: [SDL 0266] New vehicle data GearStatus
Proposal: [New vehicle data GearStatus](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0266-New-vehicle-data-GearStatus.md)

> This proposal is to add new vehicle data `GearStatus` to know drive mode and actual gear the transmission has selected.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/881

Steering Committee Decision:

>The Steering Committee voted to accept this proposal with the following revisions: use `userSelectedGear` in place of `selectedGear` and use the descriptions  for `GearStatus` included in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/881#issuecomment-573838656).
> The proposal .md file was updated to reflect these revisions on 1/21/2020.

### PR DESCRIPTION
**Pull request by MSavitsk**
Fixes #255

This PR is **[ready]** for review.

### Risk
This PR makes **[minor]** API changes.

### Testing Plan
Covered by existing unit tests.

### Summary
Applied [[SDL 0266] New vehicle data GearStatus](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0266-New-vehicle-data-GearStatus.md) changes

##### Enhancements
* Added required getters/setters in related RPC classes

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform) and this pull request adheres to the [Contributing Guide](./CONTRIBUTING.md).

### CODE REVIEW

**Comment by MSavitsk** [comment]
@kshala-ford @mrapitis please review the changes.

**Comment by santhanamk** [comment]
@MSavitsk I reviewed your PR.  Below, are my suggestions.

**Source code changes:**

_VehicleDataType.js:_
 - are you able to indicate that `VEHICLEDATA_GEARSTATUS` started since X.x?
 - are you able to indicate that `VEHICLEDATA_PRNDL` ended in X.x?

For _SubscribeVehicleData.js_, _UnsubscribeVehicleData.js_, _GetVehicleData.js_, _SubscribeVehicleDataResponse.js_, _UnsubscribeVehicleDataResponse.js_, _GetVehicleDataResponse.js_, _OnVehicleData.js_, _SubscribeVehicleData.js:_
 - are you able to indicate that the `prndl` parameter is deprecated since X.x?

**Unit Test changes:**

_Test.js:_
 - Does Test.js need the enums `TransmissionType`, `PRNDL` and the struct `GearStatus`?


Can you add unit tests for enums `TransmissionType` and `PRNDL`?  I think they would go under tests/node/rpc/enums.
Can you add unit tests for struct `GearStatus`?  I think they would go under tests/node/rpc/structs.

**Comment by vladmu** [comment]
@santhanamk thank you for review.

> **Source code changes:**
> 
> _VehicleDataType.js:_
> 
> * are you able to indicate that `VEHICLEDATA_GEARSTATUS` started since X.x?
> * are you able to indicate that `VEHICLEDATA_PRNDL` ended in X.x?
> 
> For _SubscribeVehicleData.js_, _UnsubscribeVehicleData.js_, _GetVehicleData.js_, _SubscribeVehicleDataResponse.js_, _UnsubscribeVehicleDataResponse.js_, _GetVehicleDataResponse.js_, _OnVehicleData.js_, _SubscribeVehicleData.js:_
> 
> * are you able to indicate that the `prndl` parameter is deprecated since X.x?

The provided changes were generated by the RPC generator based on changes in the rpc_spec/MOBILE_API.xml: https://github.com/smartdevicelink/rpc_spec/pull/252/files
So we expect that all required indications should be there before putting them into JS code. Please note that the generator doesn't take into account the `since` and `until` attributes, no RPC classes in the library include that for now. So we expect that enum values and function parameters include needed indications in the `description` tag to meet this your point.

> **Unit Test changes:**
> 
> _Test.js:_
> 
> * Does Test.js need the enums `TransmissionType`, `PRNDL` and the struct `GearStatus`?
> 
> Can you add unit tests for enums `TransmissionType` and `PRNDL`? I think they would go under tests/node/rpc/enums.
> Can you add unit tests for struct `GearStatus`? I think they would go under tests/node/rpc/structs.

I will check the existing tests and add the required or answer here a little bit later.

**Comment by santhanamk** [comment]
Sounds good @vladmu.  Please let me know when you want me to review the code again.

**Comment by vladmu** [comment]
@santhanamk We've added unit tests, please review.

**Comment by santhanamk** [comment]
@theresalech this PR is ready for Livio review.

**Comment by renonick87** [comment]
I'm approving this PR but will wait to merge it until after version 1.1 of the sdl_javascript_suite has been released. At that point the SDL.min.js files will have to be rebuilt to resolve the merge conflicts.

**Comment by vladmu** [comment]
> I'm approving this PR but will wait to merge it until after version 1.1 of the sdl_javascript_suite has been released. At that point the SDL.min.js files will have to be rebuilt to resolve the merge conflicts.

Thank you @renonick87, I suppose the same situation will be with all other vehicle data PRs. Moreover they could be merged only one after one with resolving conflicts in common code sources and unit tests. Please let us know here when we need to update minified distributions to resolve conflicts.

**Comment by crokita** [comment]
While we continue our review of this PR, please pull in the new changes from the develop branch. We are removing the built files from the project so that merge conflicts will stop happening with them and the processing of contributing and reviewing code will be easier.
@MSavitsk

**Comment by vladmu** [comment]
@crokita the branch is refreshed with new changes from develop. Please review.

**Comment by renonick87** [comment]
@MSavitsk  This PR is approved, however the unit tests are causing merge conflicts that need to be addressed. Please update so we can continue.

**Comment by renonick87** [comment]
@vladmu I believe this is the last of the vehicle data PRs with conflicts to be resolved. Thank you for your assistance in these.

**Comment by vladmu** [comment]
> @vladmu I believe this is the last of the vehicle data PRs with conflicts to be resolved. Thank you for your assistance in these.

@renonick87 done, please review. Thank you!

**Pull request merged**
