### PR TITLE
[SDL 0257] New vehicle data HandsOffSteering

### LINKED ISSUE #251: [SDL 0257] New vehicle data HandsOffSteering
Proposal: [New vehicle data HandsOffSteering](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0257-New-vehicle-data-HandsOffSteering.md)

> This proposal is to add new vehicle data `HandsOffSteering` to know whether or not a driver has his or her hands on the steering wheel.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/857

### PR DESCRIPTION
**Pull request by vladmu**
Fixes #251

This PR is **[ready]** for review.

### Risk
This PR makes **[minor]** API changes.

### Testing Plan
Covered by existing unit tests.

### Summary
Applied [[SDL 0257] New vehicle data HandsOffSteering](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0257-New-vehicle-data-HandsOffSteering.md) changes

##### Enhancements
* Added required getters/setters in related RPC classes

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform) and this pull request adheres to the [Contributing Guide](./CONTRIBUTING.md).

### CODE REVIEW

**Comment by vladmu** [comment]
@kshala-ford @mrapitis please review the changes.

**Comment by santhanamk** [comment]
Hi @vladmu I reviewed your PR.  Code looks good.

**Comment by vladmu** [comment]
@theresalech, @crokita this PR is ready for review.

**Comment by theresalech** [comment]
@vladmu, can you please advise if Ford has reviewed and approved?  Thanks!

**Comment by vladmu** [comment]
@theresalech yes, Ford reviewed and approved this PR before we did open it for PMs review. @santhanamk to avoid such misleading next time I'd be thankful if you could write in comments that "Ford reviewed and approved the PR" when you finished the review of our PRs. Thank you!

**Comment by santhanamk** [comment]
> @theresalech yes, Ford reviewed and approved this PR before we did open it for PMs review. @santhanamk to avoid such misleading next time I'd be thankful if you could write in comments that "Ford reviewed and approved the PR" when you finished the review of our PRs. Thank you!

sure will do.

**Comment by santhanamk** [comment]
@theresalech this PR is ready for Livio review.

**Comment by crokita** [comment]
While we continue our review of this PR, please pull in the new changes from the develop branch. We are removing the built files from the project so that merge conflicts will stop happening with them and the processing of contributing and reviewing code will be easier.
@vladmu

**Comment by vladmu** [comment]
@crokita the branch is refreshed with new changes from develop. Please review.

**Comment by renonick87** [comment]
@vladmu This PR looks good, however there are merge conflicts. Please update so we can continue.

**Comment by vladmu** [comment]
> @vladmu This PR looks good, however there are merge conflicts. Please update so we can continue.

@renonick87 I have resolved conflicts here, but for avoiding the double work, it would be better to merge VehicleData related PRs one-by-one, almost all of them provide changes to the same files. So I'll wait for your approval and merging of this PR then please let me know what PR I should focus after. Thank you!

**Pull request merged**
